/**
 * API capability matrix (spec #117): resource, operation, endpoint, version,
 * read/write, implemented, tested, permissions, pagination, rate-limit impact,
 * notes + known limitations. Verified against the current official
 * developer.helpscout.com Inbox API 2.0 documentation (fetched at build time).
 */
export interface CapabilityRow {
  resource: string;
  operation: string;
  endpoint: string;
  api_version: 'v2' | 'v3' | '-';
  read_write: 'read' | 'write' | 'read/write' | 'auth';
  implemented: boolean;
  tested: boolean;
  permission: string;
  pagination: string;
  rate_limit_impact: string;
  notes: string;
}

export const CAPABILITY_MATRIX: CapabilityRow[] = [
  { resource: 'users', operation: 'Get resource owner', endpoint: 'GET /v2/users/me', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'authenticated user', pagination: 'none', rate_limit_impact: '1 read', notes: 'Used for connection test + account bootstrap.' },
  { resource: 'users', operation: 'List users', endpoint: 'GET /v2/users', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page (50/page)', rate_limit_impact: '1 read per page', notes: '' },
  { resource: 'users', operation: 'Get user statuses', endpoint: 'GET /v2/users/{id}/status', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: '1 read per user', notes: '' },
  { resource: 'system-users', operation: 'List system users', endpoint: 'GET /v3/system-users', api_version: 'v3', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page (50/page)', rate_limit_impact: '1 read per page', notes: 'Includes AI Agent system users.' },
  { resource: 'teams', operation: 'List teams', endpoint: 'GET /v2/teams', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per page', notes: '' },
  { resource: 'teams', operation: 'List team members', endpoint: 'GET /v2/teams/{id}/members', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per team', notes: '' },
  { resource: 'mailboxes', operation: 'List inboxes', endpoint: 'GET /v2/mailboxes', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read', notes: '' },
  { resource: 'mailboxes', operation: 'List folders', endpoint: 'GET /v2/mailboxes/{id}/folders', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per inbox', notes: '' },
  { resource: 'mailboxes', operation: 'List inbox custom fields', endpoint: 'GET /v2/mailboxes/{id}/fields', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per inbox', notes: 'Distinguishes systemType fields (topic/sentiment).' },
  { resource: 'mailboxes', operation: 'List saved replies', endpoint: 'GET /v2/mailboxes/{id}/saved-replies', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: '1 read per inbox', notes: '' },
  { resource: 'mailboxes', operation: 'Get routing configuration', endpoint: 'GET /v2/mailboxes/{id}/routing', api_version: 'v2', read_write: 'read', implemented: true, tested: false, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: 'Read-only display.' },
  { resource: 'conversations', operation: 'List conversations', endpoint: 'GET /v3/conversations', api_version: 'v3', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'cursor (25/page)', rate_limit_impact: '1 read per page', notes: 'Primary sync mechanism; modifiedSince incremental + status=all backfill; embed=threads used for backfill.' },
  { resource: 'conversations', operation: 'Get conversation', endpoint: 'GET /v3/conversations/{id}', api_version: 'v3', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: '301 + Location when merged - handled.' },
  { resource: 'conversations', operation: 'List threads', endpoint: 'GET /v3/conversations/{id}/threads', api_version: 'v3', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per conversation', notes: 'Returns real system_user types (v3 behavior).' },
  { resource: 'conversations', operation: 'Create reply thread', endpoint: 'POST /v2/conversations/{id}/reply', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: 'Supports draft, status after send, assignTo, cc/bcc, base64 attachments.' },
  { resource: 'conversations', operation: 'Create note thread', endpoint: 'POST /v2/conversations/{id}/notes', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: '' },
  { resource: 'conversations', operation: 'Update conversation (JSON Patch)', endpoint: 'PATCH /v2/conversations/{id}', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double per op', notes: 'subject/status/assignTo(+remove)/mailboxId(move)/primaryCustomer.id/draft publish.' },
  { resource: 'conversations', operation: 'Update tags (replacement)', endpoint: 'PUT /v2/conversations/{id}/tags', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: 'Full replacement semantics; SupportOS always fresh-reads and merges to avoid stale overwrite.' },
  { resource: 'conversations', operation: 'Update custom fields (replacement)', endpoint: 'PUT /v2/conversations/{id}/fields', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: 'System fields preserved when omitted (documented); merged fresh state.' },
  { resource: 'conversations', operation: 'Snooze / unsnooze', endpoint: 'PUT/DELETE /v2/conversations/{id}/snooze', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: '' },
  { resource: 'conversations', operation: 'Schedule thread', endpoint: 'PUT /v2/conversations/{id}/threads/{tid}/schedule', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: 'Also publish (PATCH state=published) and delete schedule.' },
  { resource: 'attachments', operation: 'Get attachment data', endpoint: 'GET /v2/conversations/{id}/attachments/{aid}/data', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: 'Base64 payload; stored locally with hash; never executed.' },
  { resource: 'customers', operation: 'List customers', endpoint: 'GET /v3/customers', api_version: 'v3', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'cursor (50/page)', rate_limit_impact: '1 read per page', notes: 'modifiedSince incremental sync.' },
  { resource: 'customers', operation: 'Get customer', endpoint: 'GET /v2/customers/{id}', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: '' },
  { resource: 'organizations', operation: 'List organizations', endpoint: 'GET /v2/organizations', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per page', notes: '' },
  { resource: 'properties', operation: 'List customer/organization property definitions', endpoint: 'GET /v2/{context}-properties', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read', notes: '' },
  { resource: 'tags', operation: 'List tags', endpoint: 'GET /v2/tags', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read per page', notes: 'Tags are created implicitly by name via conversation tag updates (documented).' },
  { resource: 'ratings', operation: 'Get satisfaction rating', endpoint: 'GET /v2/ratings/{id}', api_version: 'v2', read_write: 'read', implemented: true, tested: false, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: 'KNOWN LIMITATION: no documented list-ratings polling endpoint; ratings primarily arrive via the satisfaction.ratings webhook. Demo mode provides seeded ratings.' },
  { resource: 'workflows', operation: 'List workflows', endpoint: 'GET /v2/workflows', api_version: 'v2', read_write: 'read', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read', notes: '' },
  { resource: 'workflows', operation: 'Run manual workflow on conversation', endpoint: 'POST /v2/workflows/{id}/run', api_version: 'v2', read_write: 'write', implemented: true, tested: true, permission: 'user', pagination: 'none', rate_limit_impact: 'counts double', notes: 'This is Help Scout workflows - clearly distinct from local SupportOS automation.' },
  { resource: 'webhooks', operation: 'List/create/delete webhooks', endpoint: 'GET/POST/DELETE /v2/webhooks', api_version: 'v2', read_write: 'read/write', implemented: true, tested: true, permission: 'user', pagination: 'page', rate_limit_impact: '1 read', notes: 'Inbound events verified with X-HelpScout-Signature (base64 HMAC-SHA1 of raw body). Localhost requires a relay.' },
  { resource: 'reports', operation: 'Company overall', endpoint: 'GET /v2/reports/company', api_version: 'v2', read_write: 'read', implemented: true, tested: false, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: 'Report params: start/end.' },
  { resource: 'reports', operation: 'Conversations overall', endpoint: 'GET /v2/reports/conversations', api_version: 'v2', read_write: 'read', implemented: true, tested: false, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: '' },
  { resource: 'reports', operation: 'Happiness ratings', endpoint: 'GET /v2/reports/happiness', api_version: 'v2', read_write: 'read', implemented: true, tested: false, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: '' },
  { resource: 'reports', operation: 'Productivity overall', endpoint: 'GET /v2/reports/productivity', api_version: 'v2', read_write: 'read', implemented: true, tested: false, permission: 'user', pagination: 'none', rate_limit_impact: '1 read', notes: '' },
  { resource: 'oauth', operation: 'Authorization Code flow', endpoint: 'authorizeClientApplication + POST /v2/oauth2/token', api_version: 'v2', read_write: 'auth', implemented: true, tested: true, permission: 'OAuth app', pagination: 'none', rate_limit_impact: 'n/a', notes: 'Tokens stored server-side only; refresh handled automatically.' },
  { resource: 'oauth', operation: 'Client Credentials flow', endpoint: 'POST /v2/oauth2/token', api_version: 'v2', read_write: 'auth', implemented: true, tested: true, permission: 'OAuth app (internal)', pagination: 'none', rate_limit_impact: 'n/a', notes: 'Simplest for a personal local integration.' },
  { resource: 'chat-api', operation: 'Chat API', endpoint: 'n/a', api_version: 'v2', read_write: 'read', implemented: false, tested: false, permission: '-', pagination: '-', rate_limit_impact: '-', notes: 'FUTURE EXTENSION: chat threads already appear via conversation v3 endpoints; full Chat API is out of scope for v1 (spec #5).' },
  { resource: 'docs-api', operation: 'Docs API', endpoint: 'n/a', api_version: '-', read_write: 'read', implemented: false, tested: false, permission: '-', pagination: '-', rate_limit_impact: '-', notes: 'FUTURE EXTENSION: local knowledge ingestion covers the core need in v1 (spec #5).' },
  { resource: 'beacon', operation: 'Beacon API', endpoint: 'n/a', api_version: '-', read_write: 'read', implemented: false, tested: false, permission: '-', pagination: '-', rate_limit_impact: '-', notes: 'FUTURE EXTENSION (spec #5).' }
];
