import { useEffect, useRef, useState, type ReactNode } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Bot, Send, Sparkles, Trash2, Copy, ShieldCheck } from 'lucide-react';
import { api } from '../../api/client.js';
import { copilotChat, useCopilotStarterQuestions } from '../../api/hooks.js';
import { Spinner, ErrorState, EmptyState } from '../common/ui.js';
import { useUiStore } from '../../state/uiStore.js';
import type { CopilotMessage, CopilotCitation } from '../../../shared/types.js';

/**
 * Local Copilot panel (v1.9.0 / M3, plan Phase 15) - a third tab in the
 * conversation context pane.
 *
 * Visible safety copy (matching the architecture):
 * - READ-ONLY: the Copilot can only call allowlisted read tools; it never
 *   writes to Help Scout and never sends anything to the customer.
 * - Cited answers: the source list is generated by the SERVER from the tools
 *   it actually executed - the model cannot fabricate citations.
 * - Honest unavailability: if LM Studio is off/unreachable the panel says so
 *   instead of pretending.
 */
export function CopilotPanel({ conversationId }: { conversationId: number }): ReactNode {
  const [sessionId, setSessionId] = useState<number | null>(null);
  const [messages, setMessages] = useState<CopilotMessage[]>([]);
  const [question, setQuestion] = useState('');
  const [sending, setSending] = useState(false);
  const [failure, setFailure] = useState<string | null>(null);
  const { data: starters, isLoading: startersLoading } = useCopilotStarterQuestions(conversationId);
  const pushToast = useUiStore((s) => s.pushToast);
  const qc = useQueryClient();
  const listRef = useRef<HTMLDivElement | null>(null);

  // Load the most recent session for this conversation on mount.
  const { data: sessionsData } = useQuery({
    queryKey: ['copilot-sessions-panel', conversationId],
    queryFn: () => api.get<{ sessions: { id: number; conversation_id: number | null; message_count: number; updated_at: string }[] }>('/api/copilot/sessions?limit=50'),
    refetchInterval: 60_000
  });

  useEffect(() => {
    const mine = (sessionsData?.sessions ?? []).filter((s) => s.conversation_id === conversationId);
    const latest = mine[0];
    if (sessionId == null && latest != null) {
      setSessionId(latest.id);
      api.get<{ session: { id: number }; messages: CopilotMessage[] }>(`/api/copilot/sessions/${latest.id}`)
        .then((r) => setMessages(r.messages))
        .catch(() => undefined);
    }
  }, [sessionsData, sessionId, conversationId]);

  useEffect(() => {
    if (listRef.current) listRef.current.scrollTop = listRef.current.scrollHeight;
  }, [messages.length, sending]);

  const ask = (q: string): void => {
    const text = q.trim();
    if (!text || sending) return;
    setSending(true);
    setFailure(null);
    setQuestion('');
    copilotChat({ question: text, conversationId, sessionId })
      .then((res) => {
        setSessionId(res.session.id);
        setMessages((prev) => [...prev.filter((m) => m.role !== 'tool'), res.user_message, res.assistant_message]);
        void qc.invalidateQueries({ queryKey: ['copilot-sessions-panel', conversationId] });
      })
      .catch((e: unknown) => {
        setFailure(e instanceof Error ? e.message : 'The Copilot could not answer. Check the LM Studio connection in Settings.');
      })
      .finally(() => setSending(false));
  };

  const deleteSession = (): void => {
    if (sessionId == null) return;
    api.delete(`/api/copilot/sessions/${sessionId}`)
      .then(() => {
        setSessionId(null);
        setMessages([]);
        void qc.invalidateQueries({ queryKey: ['copilot-sessions-panel', conversationId] });
        pushToast({ kind: 'success', message: 'Copilot session deleted.' });
      })
      .catch(() => pushToast({ kind: 'error', message: 'Could not delete the session.' }));
  };

  return (
    <div className="copilot-panel">
      <div className="flex-between" style={{ padding: '8px 12px' }}>
        <h3 className="card-title" style={{ margin: 0 }}>
          <Bot size={14} /> Local Copilot
          <span className="badge tag" title="Read-only tools; never writes to Help Scout; runs fully locally via LM Studio">read-only · local</span>
        </h3>
        {sessionId != null ? (
          <button className="btn ghost small" onClick={deleteSession} title="Delete this session">
            <Trash2 size={11} />
          </button>
        ) : null}
      </div>

      <div className="copilot-safety" style={{ margin: '0 12px 6px' }}>
        <ShieldCheck size={11} /> Answers cite local evidence from read-only tools. Nothing is sent to the customer.
      </div>

      <div className="copilot-list" ref={listRef}>
        {messages.length === 0 ? (
          <div style={{ padding: '4px 12px 8px' }}>
            {startersLoading ? <Spinner label="Preparing suggestions" /> : (
              <>
                <p className="text-xs muted" style={{ marginTop: 0 }}>Start with a question, or pick one:</p>
                <div className="flex wrap" style={{ gap: 6 }}>
                  {(starters?.questions ?? []).slice(0, 8).map((s) => (
                    <button key={s.question} className="chip" title={s.why} onClick={() => ask(s.question)}>
                      <Sparkles size={10} /> {s.question}
                    </button>
                  ))}
                </div>
              </>
            )}
          </div>
        ) : (
          messages.map((m) => <CopilotMessageView key={m.id} message={m} />)
        )}
        {sending ? (
          <div className="copilot-msg assistant" style={{ opacity: 0.7 }}>
            <strong className="text-xs">Copilot</strong>
            <Spinner label="Thinking (local model)" />
          </div>
        ) : null}
        {failure ? (
          <div style={{ margin: '6px 12px' }}>
            <ErrorState message="The Copilot is unavailable." detail={failure} />
          </div>
        ) : null}
      </div>

      <form
        className="copilot-composer"
        onSubmit={(e) => {
          e.preventDefault();
          ask(question);
        }}
      >
        <input
          className="input"
          placeholder="Ask about this ticket, the customer, past cases, docs..."
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          maxLength={4000}
          disabled={sending}
          aria-label="Ask the Local Copilot"
        />
        <button className="btn small" type="submit" disabled={sending || question.trim().length === 0}>
          <Send size={11} /> Ask
        </button>
      </form>
    </div>
  );
}

function CopilotMessageView({ message }: { message: CopilotMessage }): ReactNode {
  if (message.role === 'user') {
    return (
      <div className="copilot-msg user">
        <strong className="text-xs">You</strong>
        <p style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{message.content}</p>
      </div>
    );
  }
  return (
    <div className="copilot-msg assistant">
      <strong className="text-xs">
        Copilot {message.tool_calls > 0 ? <span className="badge tag" title="Number of read-only tool calls used">{message.tool_calls} tool call{message.tool_calls === 1 ? '' : 's'}</span> : null}
      </strong>
      <p style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{message.content}</p>
      {message.citations.length > 0 ? <CitationList citations={message.citations} /> : null}
    </div>
  );
}

function CitationList({ citations }: { citations: CopilotCitation[] }): ReactNode {
  const pushToast = useUiStore((s) => s.pushToast);
  // v2.2.1 audit fix: this component used to dispatch a 'sos:navigate' custom
  // event that NOTHING in the app listens to - the citation "open" link was a
  // dead control. Use the router directly.
  const navigate = useNavigate();
  return (
    <div className="copilot-citations">
      <div className="text-xs muted">Sources (from tools the server actually executed):</div>
      {citations.map((c) => (
        <div key={c.index} className="copilot-citation-row">
          <span className="cite-index">[{c.index}]</span>
          <span className="text-xs">{c.label}</span>
          {c.conversation_id != null ? (
            <a className="text-xs" href={`/inbox/conversation/${c.conversation_id}`} onClick={(e) => { e.preventDefault(); navigate(`/inbox/conversation/${c.conversation_id}`); }}>
              open
            </a>
          ) : null}
          <button
            className="btn ghost small"
            title="Copy citation"
            onClick={() => {
              void navigator.clipboard?.writeText(`[${c.index}] ${c.label}`);
              pushToast({ kind: 'success', message: 'Citation copied.' });
            }}
          >
            <Copy size={10} />
          </button>
        </div>
      ))}
    </div>
  );
}

/** Standalone Copilot page section (AiCenter tab reuses the panel without a conversation). */
export function CopilotGlobal(): ReactNode {
  return (
    <div className="page">
      <div className="card">
        <EmptyState
          icon="bot"
          title="The Local Copilot lives inside conversations"
          hint="Open any conversation and switch the context pane to the Copilot tab. It answers with local evidence: this ticket, the customer's history, similar cases, known issues, docs and the AI attribute layer."
        />
      </div>
    </div>
  );
}
